name = "meSch"
uuid = "a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"
authors = ["Kaleb Ben Naveed <kalebbennaveed@gmail.com>"]
version = "0.1.0"

[deps]
BlockDiagonals = "0a1fb500-61f7-11e9-3c65-f5ef3456f9f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
ECOS = "e2685f51-7e38-5353-a97d-a921fd2c8199"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MeshCat = "283c5d60-a78f-5afe-a0af-af636b173e11"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TrajOptPlots = "7770976a-8dee-4930-bf39-a1782fd21ce6"
